# You can get this from your VRChat profile URL. VRCX or VRChat Home can provide this.
your_user_id = "usr_10581b0d-08d2-4742-8e8c-e8b698696d33"

# Path to your VRCX database. It'll be whatever "%appdata%\VRCX\VRCX.sqlite3" expands to.
vrcx_db_path = "C:\\Users\\johnsmith\\AppData\\Roaming\\VRCX"

# If two events are this far apart or less, then assume VRCX was running the whole time
vrcx_running_detection_threshold_minutes = 30

# How long should a bucket be?
bucket_duration_minutes = 10

# Should values be normalized to remove bias? Bias can be introduced if you only run VRCX at particular times (e.g. when you're awake). This will make the output data noisier, which can only be mitigated by collecting a LOT of data.
normalize = true

# Optionally, you can provide an array of friend ids here to ONLY show those friends. Omit this line entirely to show all friends.
#friend_ids = ["usr_80d8bbe0-2040-406c-bb4f-0cf0cf9a6c49", "usr_84b47dcc-c1bd-4457-b0ea-357ad3a2cf2c", "usr_645a17a0-4118-436a-9604-37f587bbe8d4", "usr_52eac624-cbce-45ac-a409-863f2affe520", "usr_43916fcd-491b-4746-9428-86b08fdfb629", "usr_12fd610d-369f-4a33-81da-fbb8b7b28c16", "usr_62956bf2-1ed0-487e-9215-b2ad597e206d", "usr_1e3e5f0f-7506-4319-8575-bec5f4262080", "usr_8765fbf6-b9ac-4a28-9774-d1d5152e24d0", "usr_3030d6b1-b38e-480b-a72a-f5ee2741cf39"]
