# Copyright 2022 Michael Ripley
# This file is part of vrcx-optimal-time.
# vrcx-optimal-time is licensed under the MIT license (see LICENSE file for details).

name: Build
on: push
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' # only run for pushes to tags or master
    strategy:
      matrix:
        target:
          - runs-on: windows-latest
            triple: x86_64-pc-windows-msvc
            build-name: Windows
            artifact-name: windows-x64
            suffix: .exe
          - runs-on: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
            build-name: Linux
            artifact-name: linux-x64
            suffix: ''
          - runs-on: macos-latest
            triple: x86_64-apple-darwin
            build-name: macOS
            artifact-name: mac-x64
            suffix: ''
      fail-fast: false
    name: Build ${{ matrix.target.build-name }}
    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Setup workflow cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target.triple }}
      - name: Install extra Linux dependencies
        if: matrix.target.runs-on == 'ubuntu-latest'
        run: sudo apt-get install -y libdbus-1-dev pkg-config libudev-dev # libdbus-sys needs {ibdbus-1-dev, pkg-config}. libudev-sys needs {libudev-dev}
      - name: Build
        run: cargo build --release --target ${{ matrix.target.triple }}
      - name: Upload workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: vrcx-optimal-time-${{ matrix.target.triple }}
          path: ./target/${{ matrix.target.triple }}/release/vrcx-optimal-time${{ matrix.target.suffix }}
          if-no-files-found: error
      - name: Rename artifact for release # action-gh-release is incapable of renaming files, so I have to do it manually
        if: startsWith(github.ref, 'refs/tags/') # only run for pushes to tags
        run: cp "./target/${{ matrix.target.triple }}/release/vrcx-optimal-time${{ matrix.target.suffix }}" "${{ runner.temp }}/vrcx-optimal-time-${{ matrix.target.artifact-name }}${{ matrix.target.suffix }}"
        shell: bash
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # only run for pushes to tags
        with:
          draft: true
          files: ${{ runner.temp }}/vrcx-optimal-time-${{ matrix.target.artifact-name }}${{ matrix.target.suffix }}
          fail_on_unmatched_files: true
